services:
  ui:
    build:
      context: ui
      dockerfile: prod.Dockerfile
    image: ui-prod
    volumes:
      - ./ui/:/app
      - astro_node_modules:/app/node_modules
    restart: "on-failure"
    ports:
      - 4321:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"
   
    
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
    ports:
      - 7800:7800

volumes:
  astro_node_modules: