services:
  bionet-ui:
    build:
      context: bionet-ui
      dockerfile: dev.Dockerfile
    image: bionet-ui
    volumes:
      - ./bionet-ui/:/app
      - astro_node_modules:/app/node_modules
    restart: 'no'
    expose:
      - 4321
    
  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
    ports:
      - 7800:7800

volumes:
  astro_node_modules: