apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bionet-ui-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bionet-ui-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10