apiVersion: v1
kind: Service
metadata:
  name: bionet-ui-service
spec:
  type: LoadBalancer
  ports:
    - port: 4321
      targetPort: 4321
      protocol: TCP
      nodePort: 31000
  selector:
    app: bionet-ui